### PR TITLE
Add new icon

### PR DESCRIPTION
**Pull request by shalva97**
Screenshot 2023-03-08 at 14 59 07

looks a bit better now

### CODE REVIEW

**Review by Nodrex — APPROVED** [review]
Why do we have a purple background?

**Comment by shalva97** [comment]
good question, I dont know... Will remove soon

**Comment by shalva97** [comment]
okay the website I used generated png files, but svg works just fine. Will refactor this later

**Comment by Nodrex** [comment]
> okay the website I used generated png files, but svg works just fine. Will refactor this later

Ok

**Review by Nodrex — APPROVED** [review]

**Pull request merged**
