### PR TITLE
adding version catalog

### PR DESCRIPTION
**Pull request by shalva97**
There is lots to replace, maybe we can split the work? this is very repetitive

Also autocomplete does not work for Groovy. we have to migrate to .kts

### CODE REVIEW

**Comment by Nodrex** [comment]
> Also autocomplete does not work for Groovy. we have to migrate to .kts

Agree with migrating to .kts

**Comment by Nodrex** [comment]
> There is lots to replace, maybe we can split the work? this is very repetitive

Yep i will help you with that

**Comment by shalva97** [comment]
- convert all libraries to Version Catalog
  - Retrofit
  - Serialization
  - Compose dependencies
  - Coroutines
  - Dagger - Hilt
  - Testing
- migrate all build files to Kotlin

**Comment by Nodrex** [comment]
> write which part you will work on
I will work on Compose and ramcosta

**Review by Nodrex — APPROVED** [review]

**Comment by Nodrex** [comment]
you converted to KTS nice

**Review by kdiakonidze — APPROVED** [review]

**Pull request merged**
